### ISSUE TITLE
リニアスケールで5より大きい値を入れて回答を編集すると「Network Error」で回答できない

### ISSUE THREAD

**Issue by cp-20** [traPtitech/anke-to#1238]
「Network Error」は500が返ってきたときに起こっていて、サーバーはpanicを起こしている。

直接的に落ちている場所:

https://github.com/traPtitech/anke-to/blob/19cb242aa68a6545a749f9b0105a0c3fc9b662b6/model/scale_labels_impl.go#L119

それが呼び出されている場所:
https://github.com/traPtitech/anke-to/blob/19cb242aa68a6545a749f9b0105a0c3fc9b662b6/router/responses.go#L339

**Comment by kaitoyama** [comment]
<担当するメンバーがまだorgにいないので仮押さえで自分つけてます>
