### ISSUE TITLE
古いOpenAPIをswaggerにv1として修正

### ISSUE THREAD

**Issue by kaitoyama** [traPtitech/anke-to#1254]
traQとかjomonみたいにしたい
(今リリースすると古いバージョンのswaggerが見られなくなってしまう)

**Comment by cp-20** [comment]
Swagger側でそれぞれ `v1` ブランチと `v3` ブランチを参照するようにしました
https://github.com/traPtitech/swagger-viewer/pull/3
https://github.com/traPtitech/swagger-viewer/pull/4
