### ISSUE TITLE
結果が見られない

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/anke-to#356]
500帰ってくる

`/api/results/*`

**Comment by yto60** [comment]
見られる
- https://anke-to.trap.jp/api/results/20

見られない (500が返る)
- https://anke-to.trap.jp/api/results/18

**Comment by mazrean** [comment]
選択肢にからの文字列があるとヤバい

**Comment by mazrean** [comment]
それ以外にも問題あるっぽい

**Comment by yto60** [comment]
そのアンケートに対して、保存された回答 (送信はされていない) が存在すると見られない？
(全部確認したわけではないですが、自分が下書き保存したことのあるアンケートの結果が見られなくなっていそうです)

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/anke-to/blob/371aecda8f4470aab477affbe4cc33cd34ad71d2/router/results.go#L27
https://github.com/traPtitech/anke-to/blob/371aecda8f4470aab477affbe4cc33cd34ad71d2/model/respondents.go#L206
保存された回答があるときはエラーが起きるのと、そもそも`GetRespondentDetail`は引数として`responseID`を受け取るのに`questionnaireID`で読んでたりいろいろおかしそうです

**Comment by sapphi-red** [comment]
- https://anke-to.trap.jp/api/results/13
- https://anke-to.trap.jp/api/results/709

**Comment by sapphi-red** [comment]
わからんけどここがやばいと思う
https://github.com/traPtitech/anke-to/blob/bde7cbd200fa921a28069dfa2c6818b588d35b8f/model/respondents.go#L317

**Comment by mazrean** [comment]
質問の追加で表示できなくなる

**Comment by mazrean** [comment]
質問削除でも表示できなくなる。

**Comment by mazrean** [comment]
↑治ったけどまだ結果見られない…
