### ISSUE TITLE
不要なif

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/anke-to#366]
https://github.com/traPtitech/anke-to/blob/371aecda8f4470aab477affbe4cc33cd34ad71d2/model/respondents.go#L203
この`if`代入されてから一度も変更されてないから常に`true`

https://github.com/traPtitech/anke-to/blob/371aecda8f4470aab477affbe4cc33cd34ad71d2/model/respondents.go#L190

ミスか変更忘れ？

**Comment by mazrean** [comment]
ifの中で`isRespondentSetted := true`すべきなのを忘れている

**Comment by mazrean** [comment]
修正。
