### ISSUE TITLE
`option_response`の並び順が不定

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/anke-to#401]
`/api/results/%d`

不定なのでstatisticsの順番がごっちゃごちゃになってる
一応クライアントでソートかければよいのでサーバーで直さなくてもよいけど破壊的変更だったのでissueにしとく

**Comment by mazrean** [comment]
たぶん現在respondentsテーブルを起点にしてJOINされている結果respondentsテーブルでの並び順、つまり先にされた回答で選ばれたものが家になって返る状態になっている(良くない)

**Comment by mazrean** [comment]
v2にする前ってどういう並び順になっていたんだ？

**Comment by sapphi-red** [comment]
質問での選択肢の順番になってた

**Comment by mazrean** [comment]
それ、クライアントで並べ直していたりしない？

**Comment by mazrean** [comment]
`/api/results/%d`は選択肢の種類ごとにまとめたりしないでそれぞれの回答を返しているだけなはずなので、並べているとしたらクライアントでやっている以外考えられない

**Comment by mazrean** [comment]
修正前の状態のコードを読んでみたのだけど、選択肢の並び順でソートしている部分がなさそうだったので
https://github.com/traPtitech/anke-to/blob/236a92e753/router/responses.go#L98-L208

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/anke-to/blob/76c6a044c7579575f2344a525406750e06e5bed8/client/src/components/Results/Statistics.vue#L107
https://github.com/traPtitech/anke-to/blob/76c6a044c7579575f2344a525406750e06e5bed8/client/src/components/Results/Statistics.vue#L130-L133
してないように見える

**Comment by sapphi-red** [comment]
ソートしなかったらprimary key順になる(仕様として明記はされないけど)からそれだったりしない？

**Comment by mazrean** [comment]
そもそも回答を返すときにoptionsテーブルを一切触っていないから質問での並び順を手に入れる手段がないはず

**Comment by sapphi-red** [comment]
ごめん、ぼくの記憶違いかも
