### ISSUE TITLE
保存済み回答があるときに/targetedで回答済み扱いになる

### ISSUE THREAD

**Issue by mazrean** [traPtitech/anke-to#449]
https://github.com/traPtitech/anke-to/blob/8ecb0d96c3/model/questionnaires.go#L285-L287
で保存済み回答があるときにhas_respomseがtrueになるため、回答済み扱いになる。

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/anke-to/blob/f4a266a765a050ed8868db30c2ad993b4e175ab4/docs/swagger/swagger.yaml#L516

**Comment by mazrean** [comment]
問題なかったのでClose
