### ISSUE TITLE
"目盛り"の質問を複数作成したときに、最後の質問に登録したラベルが他の質問にも適応される

### ISSUE THREAD

**Issue by lum1narie** [traPtitech/anke-to#524]
実例

+ https://anke-to.trap.jp/questionnaires/875
+ https://anke-to.trap.jp/questionnaires/878

上のいずれも、登録段階では全ての質問にそれぞれ違うラベルを登録していた
"不満"、"満足" 及び "座学が過多"、"実習が過多"はそれぞれのanke-toの最後の目盛り型質問に割り当てたラベルである

**Comment by mazrean** [comment]
ref: #526
