### ISSUE TITLE
DBスキーマをコードで管理

### ISSUE THREAD

**Issue by tohutohu** [traPtitech/anke-to#57]
development/init.sqlに`IF NOT EXISTS`を書いて回ればとりあえず良さそう？
今後機能追加とかでDBのマイグレーションが発生することを考えると、マイグレーション系のライブラリを使ってちゃんと管理しておくと後々幸せになりそう

traQは https://github.com/traPtitech/traQ/tree/master/repository/migration ここでやっててgomigrateってのを使ってるみたいですね

**Comment by mazrean** [comment]
GORMを使うので、暫定的にはGORMのマイグレーションで良さそう。
しっかり管理するならGORMの場合既存のカラム型の変更や未使用のカラムの削除はしないので、細かく管理したい場合はgomigrateなどの他のライブラリを使うのを考えてもいいかも。

**Comment by mazrean** [comment]
GORMでのマイグレーションを実装済み。
