### ISSUE TITLE
admin関連

### ISSUE THREAD

**Issue by xxarupakaxx** [traPtitech/anke-to#715]
ここ
https://github.com/traPtitech/anke-to/blob/main/router/middleware.go#L50

**Comment by xxarupakaxx** [comment]
superAdmin(上に書かれてるIDの部員)の必要性について考えるべき？

**Comment by xxarupakaxx** [comment]
サーバー側で環境変数を置くとか？
（コードにはtraPid直書きではなくなるけど..)

**Comment by mazrean** [comment]
同じ内容のissueがあるのでClose
ref #601
