### ISSUE TITLE
作成したアンケートの再通知的なの

### ISSUE THREAD

**Issue by xxarupakaxx** [traPtitech/anke-to#722]
アンケートが作成されて一回確認したらもう一度確認されることが少ないので、だれだれが回答しましたと通知がいくようにしたりと何かしらの対策をする

**Comment by mazrean** [comment]
アプリケーション側のジョブを回して、†いい感じ†な関数の値が一番良いものをリマインドする

†いい感じ†な関数では
- 同じアンケートが連続ではリマインドされない
- リマインドすることで回答が増えるのが見込まれるアンケートで良い値を取ることが求められる

**Comment by xxarupakaxx** [comment]
アンケート建てるときにリマインドする具合を決めれればいいのではと思いました
例えば、アンケートにリマインドを
- なし
- 回答が来たら常に
- 質問を建てて1週間たってから回答が追加されたとき(一週間は任意)

**Comment by FujishigeTemma** [comment]
もともとのモチベーション: 過去の役立ち・おもしろアンケートにフィーチャーしたい
意見: その時ちやほやされて、後でディグる人がいるというのが健全。ディグるのをサポートする方向で機能を追加するのが良さそう（タグやソート、条件etc）。
dup #880
