### ISSUE TITLE
チェックボックスのみの質問で空で回答するとエラーが出る

### ISSUE THREAD

**Issue by xxarupakaxx** [traPtitech/anke-to#766]
このときのみの条件で`InsertResponse`をすると`gorm.ErrEmptySlice`が返ってくる

つまりresponsesテーブルにだけ保存できていない状況(respondentsテーブルには保存できているので表面上は回答は送信できるし削除もできる)

**Comment by xxarupakaxx** [comment]
もしかしたらクライアントの問題？

**Comment by xxarupakaxx** [comment]
https://q.trap.jp/messages/7bcc3f89-3c8f-44a4-bc7f-f70a6bc26153

**Comment by MotoyaAsahina** [comment]
#771 で修正
